version: '3.7'

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"

  airflow:
    image: 'puckel/docker-airflow:1.10.9'
    build: ./dockerfiles
    hostname: airflow
    container_name: airflow
    user: root
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ${JAVA_HOME}:/usr/local/bin/java
      - ./jar_files:/usr/local/bin/spark
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]" ]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "8080:8080"