apiVersion: v1
kind: ConfigMap
metadata:  
    name: kafka-streams-scaling-jmx-configmap
data:  
    jmx-prometheus.yml: |+
        jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:5555/jmxrmi
        lowercaseOutputName: true    
        lowercaseOutputLabelNames: true    
        ssl: false    
        rules:      
            - pattern: ".*"