apiVersion: v1
kind: Service
metadata:
  name: kafka-streams-scaling
  labels:
    app: kafka-streams-scaling
spec:
  type: ClusterIP
  ports:
    - port: 5556
      targetPort: metrics
      name: metrics
      protocol: TCP
  selector:
    app: kafka-streams-scaling
